/**
 * Enhanced Audit Logger Service
 * Captures detailed audit information for all admin actions
 */

import { Request } from "express";
import { storage } from "../storage";
import { getSecureUserId } from "../lib/anonUserHelper";

export interface AuditContext {
  userId?: string | null;
  actorEmail?: string | null;
  actorRole?: string | null;
  ipAddress?: string;
  userAgent?: string;
  sessionId?: string | null;
  requestId?: string | null;
  traceId?: string | null;
}

export interface AuditLogOptions {
  action: string;
  resource: string;
  resourceId?: string;
  details?: Record<string, any>;
  severity?: "info" | "warning" | "error" | "critical";
  category?: "auth" | "admin" | "user" | "system" | "security" | "data" | "config";
}

/**
 * Extract audit context from Express request
 */
export function extractAuditContext(req: Request): AuditContext {
  const userId = getSecureUserId(req);
  const session = req.session as any;
  const user = (req as any).user;

  const actorEmail =
    user?.claims?.email ||
    user?.email ||
    session?.passport?.user?.claims?.email ||
    session?.passport?.user?.email ||
    (user as any)?.profile?.emails?.[0]?.value ||
    null;

  const actorRole =
    user?.role ||
    user?.claims?.role ||
    session?.passport?.user?.role ||
    session?.passport?.user?.claims?.role ||
    null;

  // Prefer correlation IDs generated by our middlewares.
  const resLocals = (req as any).res?.locals || {};
  const requestId =
    (req as any).requestId ||
    resLocals.requestId ||
    (req.headers["x-request-id"] as string) ||
    null;
  const traceId = resLocals.traceId || (req.headers["x-trace-id"] as string) || null;

  const ipAddress = 
    (req.headers["x-forwarded-for"] as string)?.split(",")[0]?.trim() ||
    (req.headers["x-real-ip"] as string) ||
    req.socket?.remoteAddress ||
    req.ip ||
    "unknown";
  const userAgent = req.headers["user-agent"] || "unknown";
  const sessionId = (req as any).sessionID || req.cookies?.sessionId || null;

  return {
    userId,
    actorEmail,
    actorRole,
    ipAddress,
    userAgent,
    sessionId,
    requestId,
    traceId,
  };
}

/**
 * Create a detailed audit log entry
 */
export async function createAuditLogEntry(
  context: AuditContext,
  options: AuditLogOptions
): Promise<void> {
  try {
    const mergedDetails: Record<string, any> = { ...(options.details || {}) };

    // Persist actor identity in details for fast UI rendering without joins.
    if (context.actorEmail && mergedDetails.actorEmail == null) mergedDetails.actorEmail = context.actorEmail;
    if (context.actorRole && mergedDetails.actorRole == null) mergedDetails.actorRole = context.actorRole;

    await storage.createAuditLog({
      userId: context.userId || null,
      action: options.action,
      resource: options.resource,
      resourceId: options.resourceId,
      ipAddress: context.ipAddress,
      userAgent: context.userAgent,
      details: {
        ...mergedDetails,
        severity: options.severity || mergedDetails.severity || "info",
        category: options.category || mergedDetails.category || "system",
        sessionId: context.sessionId ?? mergedDetails.sessionId,
        requestId: context.requestId ?? mergedDetails.requestId,
        traceId: context.traceId ?? mergedDetails.traceId,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error("[AuditLogger] Failed to create audit log:", error);
  }
}

/**
 * Convenience wrapper that takes an Express request directly
 */
export async function auditLog(
  req: Request,
  options: AuditLogOptions
): Promise<void> {
  const context = extractAuditContext(req);
  await createAuditLogEntry(context, options);
}

/**
 * Pre-configured audit loggers for common actions
 */
export const AuditActions = {
  // Authentication
  AUTH_LOGIN: "auth.login",
  AUTH_LOGOUT: "auth.logout",
  AUTH_LOGIN_FAILED: "auth.login_failed",
  AUTH_PASSWORD_RESET: "auth.password_reset",
  AUTH_SESSION_CREATED: "auth.session_created",
  AUTH_SESSION_EXPIRED: "auth.session_expired",
  
  // User Management
  USER_CREATED: "user.created",
  USER_UPDATED: "user.updated",
  USER_DELETED: "user.deleted",
  USER_ROLE_CHANGED: "user.role_changed",
  USER_PLAN_CHANGED: "user.plan_changed",
  USER_STATUS_CHANGED: "user.status_changed",
  
  // Admin Actions
  ADMIN_ACCESS: "admin.access",
  ADMIN_DENIED: "admin.access_denied",
  ADMIN_SETTINGS_CHANGED: "admin.settings_changed",
  ADMIN_EXPORT_DATA: "admin.export_data",
  ADMIN_IMPORT_DATA: "admin.import_data",
  
  // AI Models
  MODEL_ENABLED: "model.enabled",
  MODEL_DISABLED: "model.disabled",
  MODEL_CONFIG_CHANGED: "model.config_changed",
  
  // Conversations
  CHAT_CREATED: "chat.created",
  CHAT_DELETED: "chat.deleted",
  CHAT_FLAGGED: "chat.flagged",
  CHAT_EXPORTED: "chat.exported",
  
  // Payments
  PAYMENT_RECEIVED: "payment.received",
  PAYMENT_FAILED: "payment.failed",
  PAYMENT_REFUNDED: "payment.refunded",
  
  // Invoices
  INVOICE_CREATED: "invoice.created",
  INVOICE_SENT: "invoice.sent",
  INVOICE_PAID: "invoice.paid",
  INVOICE_CANCELLED: "invoice.cancelled",
  
  // Security
  SECURITY_POLICY_CREATED: "security.policy_created",
  SECURITY_POLICY_UPDATED: "security.policy_updated",
  SECURITY_POLICY_DELETED: "security.policy_deleted",
  SECURITY_ALERT: "security.alert",
  SECURITY_IP_BLOCKED: "security.ip_blocked",
  SECURITY_RATE_LIMITED: "security.rate_limited",
  
  // Reports
  REPORT_GENERATED: "report.generated",
  REPORT_SCHEDULED: "report.scheduled",
  REPORT_EXPORTED: "report.exported",
  
  // Database
  DB_QUERY_EXECUTED: "db.query_executed",
  DB_BACKUP_CREATED: "db.backup_created",
  DB_MIGRATION_RUN: "db.migration_run",
  
  // System
  SYSTEM_CONFIG_CHANGED: "system.config_changed",
  SYSTEM_MAINTENANCE: "system.maintenance",
  SYSTEM_ERROR: "system.error",
} as const;

export type AuditAction = typeof AuditActions[keyof typeof AuditActions];
